import Navbar from "@/components/Navbar/Navbar";
import Providers from "@/components/Provider";
import GlobalStyles from "@/GlobalStyles/GlobalStyles";
import { getAuthSession } from "@/lib/auth";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./styles.scss";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  const session = await getAuthSession();
  return (
    <html lang="en">
      <Providers>
        <GlobalStyles>
          <body className={montserrat.className}>
            <ToastContainer
              position="top-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored"
            />
            <div className="navbar-wrapper">
              {/* @ts-expect-error Server Component */}
              <Navbar />
            </div>
            <div className="app-content-wrapper">
              {authModal}
              {children}
            </div>
          </body>
        </GlobalStyles>
      </Providers>
    </html>
  );
}
